name: Build Salt Packages

on:
  workflow_call:
    inputs:
      salt-version:
        type: string
        required: true
        description: The Salt version to set prior to building packages.
      github-hosted-runners:
        type: boolean
        required: true
      self-hosted-runners:
        type: boolean
        required: true
      cache-seed:
        required: true
        type: string
        description: Seed used to invalidate caches

env:
  PIP_INDEX_URL: https://pypi-proxy.saltstack.net/root/local/+simple/
  PIP_EXTRA_INDEX_URL: https://pypi.org/simple
  RELENV_DATA: "${{ github.workspace }}/.relenv"

jobs:

  build-deps-linux:
    name: Linux
    if: ${{ inputs.self-hosted-runners }}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        arch:
          - x86_64
          - aarch64
    runs-on:
      - self-hosted
      - linux
      - ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Relenv
        uses: ./.github/actions/setup-relenv
        with:
          platform: linux
          arch: ${{ matrix.arch }}
          cache-seed: ${{ inputs.cache-seed }}

      - name: Build 3.11
        run: |
          sudo apt install -y build-essential bison python3-all patchelf
          RELENV_PATH=$(python3 -c 'import sys, pathlib, relenv; sys.stdout.write(str(pathlib.Path(relenv.__file__).parent))')
          find $RELENV_PATH -type f -exec sed -i 's/3\.10\.9/3.11.1/g' {} \;
          find $RELENV_PATH -type f -exec sed -i 's/python3\.10/python3.11/g' {} \;
          find $RELENV_PATH -type f -exec sed -i 's/config-3\.10/config-3.11/g' {} \;
          python3 -m relenv build --arch=${{ matrix.arch }}

      - name: Setup Python Tools Scripts
        uses: ./.github/actions/setup-python-tools-scripts

      - name: Install Salt Packaging Dependencies into Relenv Onedir
        uses: ./.github/actions/build-onedir-deps
        with:
          platform: linux
          arch: ${{ matrix.arch }}
          cache-seed: ${{ inputs.cache-seed }}


  build-deps-windows:
    name: Windows
    if: ${{ inputs.github-hosted-runners }}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        arch:
          - x86
          - amd64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Relenv
        uses: ./.github/actions/setup-relenv
        with:
          platform: windows
          arch: ${{ matrix.arch }}
          cache-seed: ${{ inputs.cache-seed }}

      - name: Setup Build 3.11
        shell: bash
        run: |
          RELENV_PATH=$(python3 -c 'import sys, pathlib, relenv; sys.stdout.write(str(pathlib.Path(relenv.__file__).parent))')
          find $RELENV_PATH -type f -exec sed -i 's/3\.10\.9/3.11.1/g' {} \;
          find $RELENV_PATH -type f -exec sed -i 's/python3\.10/python3.11/g' {} \;
          find $RELENV_PATH -type f -exec sed -i 's/config-3\.10/config-3.11/g' {} \;

      - name: Build 3.11
        run: |
          python3 -m relenv build --arch=${{ matrix.arch }}

      - name: Setup Python Tools Scripts
        uses: ./.github/actions/setup-python-tools-scripts

      - name: Install Salt Packaging Dependencies into Relenv Onedir
        uses: ./.github/actions/build-onedir-deps
        with:
          platform: windows
          arch: ${{ matrix.arch }}
          cache-seed: ${{ inputs.cache-seed }}


  build-deps-macos:
    name: macOS
    if: ${{ inputs.github-hosted-runners }}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        arch:
          - x86_64
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Relenv
        uses: ./.github/actions/setup-relenv
        with:
          platform: darwin
          arch: ${{ matrix.arch }}
          cache-seed: ${{ inputs.cache-seed }}

      - name: Build 3.11
        run: |
          brew uninstall --ignore-dependencies gettext
          brew install gnu-sed
          RELENV_PATH=$(python3 -c 'import sys, pathlib, relenv; sys.stdout.write(str(pathlib.Path(relenv.__file__).parent))')
          find $RELENV_PATH -type f -exec gnu-sed -i 's/3\.10\.9/3.11.1/g' {} \;
          find $RELENV_PATH -type f -exec gnu-sed -i 's/python3\.10/python3.11/g' {} \;
          find $RELENV_PATH -type f -exec gnu-sed -i 's/config-3\.10/config-3.11/g' {} \;
          python3 -m relenv build --arch=${{ matrix.arch }}
          brew install gettext

      - name: Setup Python Tools Scripts
        uses: ./.github/actions/setup-python-tools-scripts

      - name: Install Salt Packaging Dependencies into Relenv Onedir
        uses: ./.github/actions/build-onedir-deps
        with:
          platform: darwin
          arch: ${{ matrix.arch }}
          cache-seed: ${{ inputs.cache-seed }}
